title: Welcome to my amazing site.
author: Dimitra
email: dkyri1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
 Do not mistake this for a blog. Blogs are pointless and a waste of time. this is a WEBSITE! 

# social links
instagram_username: @dimitrakyriakoylias
github_username:  dimitrrra

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
